name: Testing Automation Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      # Automation using Any CLI
      - name: Automation using Any CLI
        run: anypoint-cli-v4 account:user:describe --client_id 113e31537f1c420790499deaae57fdbf --client_secret 7288CA2c8F7F4B46b06BC7F8d1277cC3 
